### ISSUE TITLE
Where to note an ID of a letter?

### ISSUE THREAD

**Issue by StefanDumont** [TEI-Correspondence-SIG/correspDesc#3]
In the correspDesc customization for interchange proposes ("correspBeacon") we're using `@ref` to store the URL of an edited letter. For other URLS (e.g. facsimile) we have projected to use `@corresp`. But to note an ID number of a letter there is no solution at the moment. Perhaps we can use `@key` for that purpose? It is also member of att.canonical (like `@ref`).

**Comment by rettinghaus** [comment]
If @key only holds a simple ID, how to create a correspDesc for letters found in various Publications?

**Comment by StefanDumont** [comment]
Thanks for your question! The "Correspondence Metadata Interchange" (CMI) files (formerly "correspBeacon") should always hold information for one (digital or print) scholarly edition, i.e. one correspDesc-Element points only towards one edition of a letter.

**Comment by peterstadler** [comment]
moved the issue to https://github.com/TEI-Correspondence-SIG/CMIF/issues/2, closing here
