### ISSUE TITLE
allow multiple tei:bibl as beacon source

### ISSUE THREAD

**Issue by peterstadler** [TEI-Correspondence-SIG/correspDesc#7]
This has been raised by @rettinghaus:
When you're creating an index of letters this might as well be a 'meta catalogue' comprising of several editions. Thus it would be helpful to allow several \<tei:bibl\> within \<tei:sourceDesc\> to point at from the \<tei:correspDesc\> entries.

**Comment by StefanDumont** [comment]
This is an issue we already have in correspSearch for the output of the API. As of the API version 1.0 (coming this or next week) we use the attribute `correspDesc/@source` to reference to `sourceDesc/bibl/xml:id`; that's what `@source` is intended for: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.source.html. Unfortunately `correspDesc` isn't member of att.source, so we noted the attribute in the namespace http://www.bbaw.de/telota/correspSearch.

**Comment by peterstadler** [comment]
moved the issue to https://github.com/TEI-Correspondence-SIG/CMIF/issues/3, closing here
